CXX=g++
CXXFLAGS=-g -Wall -O2
CXX_OUT_FLAG=-c
LINK_OUT_FLAG=-o
LINK_EXTRA_FLAGS=-lz3 -lpthread -lboost_system -lboost_chrono
MACRO_FLAG=-D
PROFILE_MACRO=PZ3_PROFILING
ONECORE_MACRO=PZ3_ONECORE
FG_MACRO=PZ3_FINE_GRAINED_PROF
CXX_EXT=.cpp
HXX_EXT=.hpp
EXE_EXT=
OBJ_EXT=.o
LIB_EXT=.a

