CXX=g++
CXXFLAGS=-g -Wall -O2
CXX_OUT_FLAG=-c
LINK_OUT_FLAG=-o
LINK_EXTRA_FLAGS=-lz3 -lpthread -lboost_system -lboost_chrono
MACRO_FLAG=-D
MACRO_DEFINES=PZ3_PROFILING
CXX_EXT=.cpp
HXX_EXT=.hpp
EXE_EXT=
OBJ_EXT=.o
LIB_EXT=.a

